/*
 * generated by Xtext 2.9.2
 */
package de.htwdd.sf.beleg.s70307s70429.ui.tests;

import com.google.inject.Injector;
import de.htwdd.sf.beleg.s70307s70429.ui.internal.S70307s70429Activator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return S70307s70429Activator.getInstance().getInjector("de.htwdd.sf.beleg.s70307s70429.MyDsl");
	}

}
