/**
 * generated by Xtext 2.9.2
 */
package de.htwdd.sf.beleg.s70307s70429.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fact</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.htwdd.sf.beleg.s70307s70429.myDsl.MyDslPackage#getFact()
 * @model
 * @generated
 */
public interface Fact extends EObject
{
} // Fact
