/**
 * generated by Xtext 2.9.2
 */
package de.htwdd.sf.beleg.s70307s70429.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see de.htwdd.sf.beleg.s70307s70429.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.htwdd.de/sf/beleg/s70307s70429/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = de.htwdd.sf.beleg.s70307s70429.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.impl.PrologdslImpl <em>Prologdsl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.PrologdslImpl
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.MyDslPackageImpl#getPrologdsl()
   * @generated
   */
  int PROLOGDSL = 0;

  /**
   * The feature id for the '<em><b>Prologdsl</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROLOGDSL__PROLOGDSL = 0;

  /**
   * The feature id for the '<em><b>Ex</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROLOGDSL__EX = 1;

  /**
   * The number of structural features of the '<em>Prologdsl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROLOGDSL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.ProgramImpl
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.MyDslPackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 1;

  /**
   * The feature id for the '<em><b>Clause1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__CLAUSE1 = 0;

  /**
   * The feature id for the '<em><b>Clause2</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__CLAUSE2 = 1;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.impl.ExqueryImpl <em>Exquery</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.ExqueryImpl
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.MyDslPackageImpl#getExquery()
   * @generated
   */
  int EXQUERY = 2;

  /**
   * The feature id for the '<em><b>Q</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXQUERY__Q = 0;

  /**
   * The number of structural features of the '<em>Exquery</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXQUERY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.impl.QueryImpl <em>Query</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.QueryImpl
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.MyDslPackageImpl#getQuery()
   * @generated
   */
  int QUERY = 3;

  /**
   * The feature id for the '<em><b>Query</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY__QUERY = 0;

  /**
   * The feature id for the '<em><b>Pred</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY__PRED = 1;

  /**
   * The number of structural features of the '<em>Query</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.impl.ClauseImpl <em>Clause</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.ClauseImpl
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.MyDslPackageImpl#getClause()
   * @generated
   */
  int CLAUSE = 4;

  /**
   * The feature id for the '<em><b>Fact</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLAUSE__FACT = 0;

  /**
   * The feature id for the '<em><b>Clause1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLAUSE__CLAUSE1 = 1;

  /**
   * The number of structural features of the '<em>Clause</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLAUSE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.impl.FactImpl <em>Fact</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.FactImpl
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.MyDslPackageImpl#getFact()
   * @generated
   */
  int FACT = 5;

  /**
   * The number of structural features of the '<em>Fact</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.impl.RuleImpl <em>Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.RuleImpl
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.MyDslPackageImpl#getRule()
   * @generated
   */
  int RULE = 6;

  /**
   * The feature id for the '<em><b>Q</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__Q = 0;

  /**
   * The number of structural features of the '<em>Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.impl.PredicateImpl <em>Predicate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.PredicateImpl
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.MyDslPackageImpl#getPredicate()
   * @generated
   */
  int PREDICATE = 7;

  /**
   * The feature id for the '<em><b>Pred</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE__PRED = 0;

  /**
   * The feature id for the '<em><b>T</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE__T = 1;

  /**
   * The feature id for the '<em><b>T2</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE__T2 = 2;

  /**
   * The number of structural features of the '<em>Predicate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.impl.FunctorImpl <em>Functor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.FunctorImpl
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.MyDslPackageImpl#getFunctor()
   * @generated
   */
  int FUNCTOR = 8;

  /**
   * The feature id for the '<em><b>Func</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTOR__FUNC = 0;

  /**
   * The number of structural features of the '<em>Functor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTOR_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.impl.TermImpl <em>Term</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.TermImpl
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.MyDslPackageImpl#getTerm()
   * @generated
   */
  int TERM = 9;

  /**
   * The feature id for the '<em><b>Term</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERM__TERM = 0;

  /**
   * The number of structural features of the '<em>Term</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.impl.AtomImpl <em>Atom</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.AtomImpl
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.MyDslPackageImpl#getAtom()
   * @generated
   */
  int ATOM = 10;

  /**
   * The feature id for the '<em><b>Xx</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOM__XX = 0;

  /**
   * The number of structural features of the '<em>Atom</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.impl.ListImpl <em>List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.ListImpl
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.MyDslPackageImpl#getList()
   * @generated
   */
  int LIST = 11;

  /**
   * The feature id for the '<em><b>Nel</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST__NEL = 0;

  /**
   * The number of structural features of the '<em>List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.impl.NonemptylistImpl <em>Nonemptylist</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.NonemptylistImpl
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.MyDslPackageImpl#getNonemptylist()
   * @generated
   */
  int NONEMPTYLIST = 12;

  /**
   * The feature id for the '<em><b>Folge</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NONEMPTYLIST__FOLGE = 0;

  /**
   * The feature id for the '<em><b>Atom</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NONEMPTYLIST__ATOM = 1;

  /**
   * The feature id for the '<em><b>Term</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NONEMPTYLIST__TERM = 2;

  /**
   * The number of structural features of the '<em>Nonemptylist</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NONEMPTYLIST_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.impl.FolgeImpl <em>Folge</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.FolgeImpl
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.MyDslPackageImpl#getFolge()
   * @generated
   */
  int FOLGE = 13;

  /**
   * The feature id for the '<em><b>Atom</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOLGE__ATOM = 0;

  /**
   * The feature id for the '<em><b>Atoms</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOLGE__ATOMS = 1;

  /**
   * The number of structural features of the '<em>Folge</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOLGE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.impl.IdentImpl <em>Ident</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.IdentImpl
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.MyDslPackageImpl#getIdent()
   * @generated
   */
  int IDENT = 14;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IDENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Ident</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IDENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.impl.Number2Impl <em>Number2</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.Number2Impl
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.MyDslPackageImpl#getNumber2()
   * @generated
   */
  int NUMBER2 = 15;

  /**
   * The feature id for the '<em><b>Wert</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER2__WERT = 0;

  /**
   * The number of structural features of the '<em>Number2</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER2_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.impl.Variable2Impl <em>Variable2</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.Variable2Impl
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.MyDslPackageImpl#getVariable2()
   * @generated
   */
  int VARIABLE2 = 16;

  /**
   * The feature id for the '<em><b>Var1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE2__VAR1 = 0;

  /**
   * The number of structural features of the '<em>Variable2</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE2_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Prologdsl <em>Prologdsl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Prologdsl</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.Prologdsl
   * @generated
   */
  EClass getPrologdsl();

  /**
   * Returns the meta object for the containment reference '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Prologdsl#getPrologdsl <em>Prologdsl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Prologdsl</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.Prologdsl#getPrologdsl()
   * @see #getPrologdsl()
   * @generated
   */
  EReference getPrologdsl_Prologdsl();

  /**
   * Returns the meta object for the containment reference '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Prologdsl#getEx <em>Ex</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ex</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.Prologdsl#getEx()
   * @see #getPrologdsl()
   * @generated
   */
  EReference getPrologdsl_Ex();

  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the containment reference '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Program#getClause1 <em>Clause1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Clause1</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.Program#getClause1()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Clause1();

  /**
   * Returns the meta object for the containment reference list '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Program#getClause2 <em>Clause2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Clause2</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.Program#getClause2()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Clause2();

  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Exquery <em>Exquery</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Exquery</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.Exquery
   * @generated
   */
  EClass getExquery();

  /**
   * Returns the meta object for the containment reference '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Exquery#getQ <em>Q</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Q</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.Exquery#getQ()
   * @see #getExquery()
   * @generated
   */
  EReference getExquery_Q();

  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Query <em>Query</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Query</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.Query
   * @generated
   */
  EClass getQuery();

  /**
   * Returns the meta object for the containment reference '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Query#getQuery <em>Query</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Query</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.Query#getQuery()
   * @see #getQuery()
   * @generated
   */
  EReference getQuery_Query();

  /**
   * Returns the meta object for the containment reference list '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Query#getPred <em>Pred</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Pred</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.Query#getPred()
   * @see #getQuery()
   * @generated
   */
  EReference getQuery_Pred();

  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Clause <em>Clause</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Clause</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.Clause
   * @generated
   */
  EClass getClause();

  /**
   * Returns the meta object for the containment reference '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Clause#getFact <em>Fact</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Fact</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.Clause#getFact()
   * @see #getClause()
   * @generated
   */
  EReference getClause_Fact();

  /**
   * Returns the meta object for the containment reference '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Clause#getClause1 <em>Clause1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Clause1</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.Clause#getClause1()
   * @see #getClause()
   * @generated
   */
  EReference getClause_Clause1();

  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Fact <em>Fact</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fact</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.Fact
   * @generated
   */
  EClass getFact();

  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Rule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.Rule
   * @generated
   */
  EClass getRule();

  /**
   * Returns the meta object for the containment reference '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Rule#getQ <em>Q</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Q</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.Rule#getQ()
   * @see #getRule()
   * @generated
   */
  EReference getRule_Q();

  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Predicate <em>Predicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Predicate</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.Predicate
   * @generated
   */
  EClass getPredicate();

  /**
   * Returns the meta object for the containment reference '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Predicate#getPred <em>Pred</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Pred</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.Predicate#getPred()
   * @see #getPredicate()
   * @generated
   */
  EReference getPredicate_Pred();

  /**
   * Returns the meta object for the containment reference '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Predicate#getT <em>T</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>T</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.Predicate#getT()
   * @see #getPredicate()
   * @generated
   */
  EReference getPredicate_T();

  /**
   * Returns the meta object for the containment reference list '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Predicate#getT2 <em>T2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>T2</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.Predicate#getT2()
   * @see #getPredicate()
   * @generated
   */
  EReference getPredicate_T2();

  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Functor <em>Functor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Functor</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.Functor
   * @generated
   */
  EClass getFunctor();

  /**
   * Returns the meta object for the containment reference '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Functor#getFunc <em>Func</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Func</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.Functor#getFunc()
   * @see #getFunctor()
   * @generated
   */
  EReference getFunctor_Func();

  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Term <em>Term</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Term</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.Term
   * @generated
   */
  EClass getTerm();

  /**
   * Returns the meta object for the containment reference '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Term#getTerm <em>Term</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Term</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.Term#getTerm()
   * @see #getTerm()
   * @generated
   */
  EReference getTerm_Term();

  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Atom <em>Atom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Atom</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.Atom
   * @generated
   */
  EClass getAtom();

  /**
   * Returns the meta object for the containment reference '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Atom#getXx <em>Xx</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Xx</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.Atom#getXx()
   * @see #getAtom()
   * @generated
   */
  EReference getAtom_Xx();

  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.List <em>List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>List</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.List
   * @generated
   */
  EClass getList();

  /**
   * Returns the meta object for the containment reference '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.List#getNel <em>Nel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Nel</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.List#getNel()
   * @see #getList()
   * @generated
   */
  EReference getList_Nel();

  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Nonemptylist <em>Nonemptylist</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Nonemptylist</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.Nonemptylist
   * @generated
   */
  EClass getNonemptylist();

  /**
   * Returns the meta object for the containment reference '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Nonemptylist#getFolge <em>Folge</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Folge</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.Nonemptylist#getFolge()
   * @see #getNonemptylist()
   * @generated
   */
  EReference getNonemptylist_Folge();

  /**
   * Returns the meta object for the containment reference '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Nonemptylist#getAtom <em>Atom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Atom</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.Nonemptylist#getAtom()
   * @see #getNonemptylist()
   * @generated
   */
  EReference getNonemptylist_Atom();

  /**
   * Returns the meta object for the containment reference '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Nonemptylist#getTerm <em>Term</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Term</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.Nonemptylist#getTerm()
   * @see #getNonemptylist()
   * @generated
   */
  EReference getNonemptylist_Term();

  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Folge <em>Folge</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Folge</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.Folge
   * @generated
   */
  EClass getFolge();

  /**
   * Returns the meta object for the containment reference '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Folge#getAtom <em>Atom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Atom</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.Folge#getAtom()
   * @see #getFolge()
   * @generated
   */
  EReference getFolge_Atom();

  /**
   * Returns the meta object for the containment reference list '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Folge#getAtoms <em>Atoms</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Atoms</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.Folge#getAtoms()
   * @see #getFolge()
   * @generated
   */
  EReference getFolge_Atoms();

  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Ident <em>Ident</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ident</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.Ident
   * @generated
   */
  EClass getIdent();

  /**
   * Returns the meta object for the attribute '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Ident#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.Ident#getName()
   * @see #getIdent()
   * @generated
   */
  EAttribute getIdent_Name();

  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Number2 <em>Number2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Number2</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.Number2
   * @generated
   */
  EClass getNumber2();

  /**
   * Returns the meta object for the attribute '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Number2#getWert <em>Wert</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Wert</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.Number2#getWert()
   * @see #getNumber2()
   * @generated
   */
  EAttribute getNumber2_Wert();

  /**
   * Returns the meta object for class '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Variable2 <em>Variable2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable2</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.Variable2
   * @generated
   */
  EClass getVariable2();

  /**
   * Returns the meta object for the attribute '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Variable2#getVar1 <em>Var1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Var1</em>'.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.Variable2#getVar1()
   * @see #getVariable2()
   * @generated
   */
  EAttribute getVariable2_Var1();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.impl.PrologdslImpl <em>Prologdsl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.PrologdslImpl
     * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.MyDslPackageImpl#getPrologdsl()
     * @generated
     */
    EClass PROLOGDSL = eINSTANCE.getPrologdsl();

    /**
     * The meta object literal for the '<em><b>Prologdsl</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROLOGDSL__PROLOGDSL = eINSTANCE.getPrologdsl_Prologdsl();

    /**
     * The meta object literal for the '<em><b>Ex</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROLOGDSL__EX = eINSTANCE.getPrologdsl_Ex();

    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.ProgramImpl
     * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.MyDslPackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Clause1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__CLAUSE1 = eINSTANCE.getProgram_Clause1();

    /**
     * The meta object literal for the '<em><b>Clause2</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__CLAUSE2 = eINSTANCE.getProgram_Clause2();

    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.impl.ExqueryImpl <em>Exquery</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.ExqueryImpl
     * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.MyDslPackageImpl#getExquery()
     * @generated
     */
    EClass EXQUERY = eINSTANCE.getExquery();

    /**
     * The meta object literal for the '<em><b>Q</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXQUERY__Q = eINSTANCE.getExquery_Q();

    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.impl.QueryImpl <em>Query</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.QueryImpl
     * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.MyDslPackageImpl#getQuery()
     * @generated
     */
    EClass QUERY = eINSTANCE.getQuery();

    /**
     * The meta object literal for the '<em><b>Query</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUERY__QUERY = eINSTANCE.getQuery_Query();

    /**
     * The meta object literal for the '<em><b>Pred</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUERY__PRED = eINSTANCE.getQuery_Pred();

    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.impl.ClauseImpl <em>Clause</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.ClauseImpl
     * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.MyDslPackageImpl#getClause()
     * @generated
     */
    EClass CLAUSE = eINSTANCE.getClause();

    /**
     * The meta object literal for the '<em><b>Fact</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLAUSE__FACT = eINSTANCE.getClause_Fact();

    /**
     * The meta object literal for the '<em><b>Clause1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLAUSE__CLAUSE1 = eINSTANCE.getClause_Clause1();

    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.impl.FactImpl <em>Fact</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.FactImpl
     * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.MyDslPackageImpl#getFact()
     * @generated
     */
    EClass FACT = eINSTANCE.getFact();

    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.impl.RuleImpl <em>Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.RuleImpl
     * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.MyDslPackageImpl#getRule()
     * @generated
     */
    EClass RULE = eINSTANCE.getRule();

    /**
     * The meta object literal for the '<em><b>Q</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULE__Q = eINSTANCE.getRule_Q();

    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.impl.PredicateImpl <em>Predicate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.PredicateImpl
     * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.MyDslPackageImpl#getPredicate()
     * @generated
     */
    EClass PREDICATE = eINSTANCE.getPredicate();

    /**
     * The meta object literal for the '<em><b>Pred</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PREDICATE__PRED = eINSTANCE.getPredicate_Pred();

    /**
     * The meta object literal for the '<em><b>T</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PREDICATE__T = eINSTANCE.getPredicate_T();

    /**
     * The meta object literal for the '<em><b>T2</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PREDICATE__T2 = eINSTANCE.getPredicate_T2();

    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.impl.FunctorImpl <em>Functor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.FunctorImpl
     * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.MyDslPackageImpl#getFunctor()
     * @generated
     */
    EClass FUNCTOR = eINSTANCE.getFunctor();

    /**
     * The meta object literal for the '<em><b>Func</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTOR__FUNC = eINSTANCE.getFunctor_Func();

    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.impl.TermImpl <em>Term</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.TermImpl
     * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.MyDslPackageImpl#getTerm()
     * @generated
     */
    EClass TERM = eINSTANCE.getTerm();

    /**
     * The meta object literal for the '<em><b>Term</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TERM__TERM = eINSTANCE.getTerm_Term();

    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.impl.AtomImpl <em>Atom</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.AtomImpl
     * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.MyDslPackageImpl#getAtom()
     * @generated
     */
    EClass ATOM = eINSTANCE.getAtom();

    /**
     * The meta object literal for the '<em><b>Xx</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATOM__XX = eINSTANCE.getAtom_Xx();

    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.impl.ListImpl <em>List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.ListImpl
     * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.MyDslPackageImpl#getList()
     * @generated
     */
    EClass LIST = eINSTANCE.getList();

    /**
     * The meta object literal for the '<em><b>Nel</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIST__NEL = eINSTANCE.getList_Nel();

    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.impl.NonemptylistImpl <em>Nonemptylist</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.NonemptylistImpl
     * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.MyDslPackageImpl#getNonemptylist()
     * @generated
     */
    EClass NONEMPTYLIST = eINSTANCE.getNonemptylist();

    /**
     * The meta object literal for the '<em><b>Folge</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NONEMPTYLIST__FOLGE = eINSTANCE.getNonemptylist_Folge();

    /**
     * The meta object literal for the '<em><b>Atom</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NONEMPTYLIST__ATOM = eINSTANCE.getNonemptylist_Atom();

    /**
     * The meta object literal for the '<em><b>Term</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NONEMPTYLIST__TERM = eINSTANCE.getNonemptylist_Term();

    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.impl.FolgeImpl <em>Folge</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.FolgeImpl
     * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.MyDslPackageImpl#getFolge()
     * @generated
     */
    EClass FOLGE = eINSTANCE.getFolge();

    /**
     * The meta object literal for the '<em><b>Atom</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOLGE__ATOM = eINSTANCE.getFolge_Atom();

    /**
     * The meta object literal for the '<em><b>Atoms</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOLGE__ATOMS = eINSTANCE.getFolge_Atoms();

    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.impl.IdentImpl <em>Ident</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.IdentImpl
     * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.MyDslPackageImpl#getIdent()
     * @generated
     */
    EClass IDENT = eINSTANCE.getIdent();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IDENT__NAME = eINSTANCE.getIdent_Name();

    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.impl.Number2Impl <em>Number2</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.Number2Impl
     * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.MyDslPackageImpl#getNumber2()
     * @generated
     */
    EClass NUMBER2 = eINSTANCE.getNumber2();

    /**
     * The meta object literal for the '<em><b>Wert</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUMBER2__WERT = eINSTANCE.getNumber2_Wert();

    /**
     * The meta object literal for the '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.impl.Variable2Impl <em>Variable2</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.Variable2Impl
     * @see de.htwdd.sf.beleg.s70307s70429.myDsl.impl.MyDslPackageImpl#getVariable2()
     * @generated
     */
    EClass VARIABLE2 = eINSTANCE.getVariable2();

    /**
     * The meta object literal for the '<em><b>Var1</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE2__VAR1 = eINSTANCE.getVariable2_Var1();

  }

} //MyDslPackage
