/**
 * generated by Xtext 2.9.2
 */
package de.htwdd.sf.beleg.s70307s70429.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Predicate</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Predicate#getPred <em>Pred</em>}</li>
 *   <li>{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Predicate#getT <em>T</em>}</li>
 *   <li>{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Predicate#getT2 <em>T2</em>}</li>
 * </ul>
 *
 * @see de.htwdd.sf.beleg.s70307s70429.myDsl.MyDslPackage#getPredicate()
 * @model
 * @generated
 */
public interface Predicate extends EObject
{
  /**
   * Returns the value of the '<em><b>Pred</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pred</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pred</em>' containment reference.
   * @see #setPred(Functor)
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.MyDslPackage#getPredicate_Pred()
   * @model containment="true"
   * @generated
   */
  Functor getPred();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Predicate#getPred <em>Pred</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pred</em>' containment reference.
   * @see #getPred()
   * @generated
   */
  void setPred(Functor value);

  /**
   * Returns the value of the '<em><b>T</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>T</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>T</em>' containment reference.
   * @see #setT(Term)
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.MyDslPackage#getPredicate_T()
   * @model containment="true"
   * @generated
   */
  Term getT();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Predicate#getT <em>T</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>T</em>' containment reference.
   * @see #getT()
   * @generated
   */
  void setT(Term value);

  /**
   * Returns the value of the '<em><b>T2</b></em>' containment reference list.
   * The list contents are of type {@link de.htwdd.sf.beleg.s70307s70429.myDsl.Term}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>T2</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>T2</em>' containment reference list.
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.MyDslPackage#getPredicate_T2()
   * @model containment="true"
   * @generated
   */
  EList<Term> getT2();

} // Predicate
