/**
 * generated by Xtext 2.9.2
 */
package de.htwdd.sf.beleg.s70307s70429.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Prologdsl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Prologdsl#getPrologdsl <em>Prologdsl</em>}</li>
 *   <li>{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Prologdsl#getEx <em>Ex</em>}</li>
 * </ul>
 *
 * @see de.htwdd.sf.beleg.s70307s70429.myDsl.MyDslPackage#getPrologdsl()
 * @model
 * @generated
 */
public interface Prologdsl extends EObject
{
  /**
   * Returns the value of the '<em><b>Prologdsl</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Prologdsl</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prologdsl</em>' containment reference.
   * @see #setPrologdsl(Program)
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.MyDslPackage#getPrologdsl_Prologdsl()
   * @model containment="true"
   * @generated
   */
  Program getPrologdsl();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Prologdsl#getPrologdsl <em>Prologdsl</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prologdsl</em>' containment reference.
   * @see #getPrologdsl()
   * @generated
   */
  void setPrologdsl(Program value);

  /**
   * Returns the value of the '<em><b>Ex</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ex</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ex</em>' containment reference.
   * @see #setEx(Exquery)
   * @see de.htwdd.sf.beleg.s70307s70429.myDsl.MyDslPackage#getPrologdsl_Ex()
   * @model containment="true"
   * @generated
   */
  Exquery getEx();

  /**
   * Sets the value of the '{@link de.htwdd.sf.beleg.s70307s70429.myDsl.Prologdsl#getEx <em>Ex</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ex</em>' containment reference.
   * @see #getEx()
   * @generated
   */
  void setEx(Exquery value);

} // Prologdsl
