/*
 * generated by Xtext 2.9.2
 */
package de.htwdd.sf.beleg.s70307s70429.ui;

import com.google.inject.Injector;
import de.htwdd.sf.beleg.s70307s70429.ui.internal.S70307s70429Activator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return S70307s70429Activator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return S70307s70429Activator.getInstance().getInjector(S70307s70429Activator.DE_HTWDD_SF_BELEG_S70307S70429_MYDSL);
	}
	
}
