/*
 * generated by Xtext 2.9.2
 */
package de.htwdd.sf.beleg.s70307s70429


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MyDslRuntimeModule extends AbstractMyDslRuntimeModule {
}
