/**
 * generated by Xtext 2.9.2
 */
package de.htwdd.sf.beleg.s70307s70429;

import de.htwdd.sf.beleg.s70307s70429.AbstractMyDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MyDslRuntimeModule extends AbstractMyDslRuntimeModule {
}
